# Generated by Django 5.1.7 on 2025-07-29 10:59

from django.db import migrations, models
from django.conf import settings


def seed_default_categories(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Category = apps.get_model('budget', 'Category')

    default_categories = {
        'expense': [
            'Transportation', 'Education', 'Housing', 'Food', 'Entertainment', 'Healthcare'
        ],
        'income': [
            'Freelance', 'Salary', 'Investment Income'
        ],
        'savings': [
            'Vacation', 'Emergency Fund', 'Retirement'
        ]
    }

    for user in User.objects.all():
        for transaction_type, names in default_categories.items():
            for name in names:
                if not Category.objects.filter(user=user, name=name, transaction_type=transaction_type).exists():
                    Category.objects.create(user=user, name=name, transaction_type=transaction_type, is_default=True)

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20250728_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(seed_default_categories),
    ]
